### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by UtopianElectronics** [sdushantha/instadp#8]
Hello,
The first problem is that I should navigate to `C:\Users\UtopianElectronics\AppData\Local\Programs\Python\Python39\Scripts\` and type `python instadp username` in order it working, otherwise it won't work (PATH problems?). The most important problem is the following:

```
Traceback (most recent call last):
  File "C:\Users\UtopianElectronics\AppData\Local\Programs\Python\Python39\Scripts\instadp", line 46, in <module>
    main()
  File "C:\Users\UtopianElectronics\AppData\Local\Programs\Python\Python39\Scripts\instadp", line 32, in main
    file_url = fetchDP(username)
  File "C:\Users\UtopianElectronics\AppData\Local\Programs\Python\Python39\Scripts\instadp", line 15, in fetchDP
    data = r.json()
  File "C:\Users\UtopianElectronics\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\UtopianElectronics\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\UtopianElectronics\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\UtopianElectronics\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

What's causing this and how to fix?

**Comment by sdushantha** [comment]
Seems like Instagram changed their API and the current code for `instadp` is not compatible with the API. I will have to fix this sometime in the future.

**Comment by UtopianElectronics** [comment]
@sdushantha Looks like the only working solution for now to view full-sized IG profile photos is to use [this website](https://www.instafollowers.co/instagram-profile-picture-size).
